Merged PR 138326: Remove unused regex call which can cause ArgumentException
Remove unused regex call which can cause ArgumentException. This was causing this error:

System.ArgumentException: parsing "*.js" - Quantifier {x,y} following nothing.