Update Drop.App version (#5239)
Old `drop.exe` has an issue with a recent Windows security update, which
causes failures like

```
ContentStore.Exceptions.CacheException: Could not download into the
cache: ErrorMessage=[FileNotFoundException:
System.IO.FileNotFoundException: Could not find file
'C:\_cache\contents\Shared\VSO0\ED8\ED878A5B6B0E382A858F9F34A562E42BFE8A70032E7E900F13CF4EE3621D8E4900.blob'.
```

When downloading drop data. The Azure Artifacts team recommends updating
to 18.164.29918 or newer.