JobMonitor: Fetch test run tags from a different API The previous one does not work, the new one does.
Before we had this:
```
##[error]Helix Job Monitor terminated with an unhandled exception.
      System.Net.Http.HttpRequestException: Request to https://vstmr.dev.azure.com/dnceng-public/public/_apis/testresults/runs/40914222/tags?api-version=7.1-preview.1 failed with 405 Method Not Allowed. {"count":1,"value":{"Message":"The requested resource does not support http method 'GET'."}}
         at Microsoft.DotNet.Helix.JobMonitor.AzureDevOpsService.<>c__DisplayClass24_0.<<SendForStringAsync>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/JobMonitor/Services/AzureDevOpsService.cs:line 465
      --- End of stack trace from previous location ---
         at Microsoft.DotNet.Helix.AzureDevOpsTestPublisher.RetryHelper.RetryAsync[T](Func`1 action, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/AzureDevOpsTestPublisher/RetryHelper.cs:line 17
         at Microsoft.DotNet.Helix.JobMonitor.AzureDevOpsService.SendForStringAsync(HttpMethod method, String requestUri, JToken body, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/Services/AzureDevOpsService.cs:line 452
         at Microsoft.DotNet.Helix.JobMonitor.AzureDevOpsService.SendAsync(HttpMethod method, String requestUri, JToken body, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/Services/AzureDevOpsService.cs:line 443
         at Microsoft.DotNet.Helix.JobMonitor.AzureDevOpsService.GetHelixJobNameFromRunTagsAsync(Int32 runId, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/Services/AzureDevOpsService.cs:line 187
         at Microsoft.DotNet.Helix.JobMonitor.AzureDevOpsService.GetFailedTestWorkItemsAsync(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/Services/AzureDevOpsService.cs:line 132
         at Microsoft.DotNet.Helix.JobMonitor.JobMonitorRunner.ExecuteRetryPassAsync(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/JobMonitorRunner.cs:line 145
         at Microsoft.DotNet.Helix.JobMonitor.JobMonitorRunner.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobMonitor/JobMonitorRunner.cs:line 94
         at Microsoft.DotNet.Helix.JobMonitor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.Helix/JobMonitor/Program.cs:line 86
```